const AUTH_USER = "AUTH_USER";
const LOGOUT_USER = "LOGOUT_USER";
const AUTH_LOADING = "AUTH_LOADING";
const AUTH_ERROR = "AUTH_ERROR";
const STOP_LOADING = "STOP_LOADING";

export { AUTH_USER, LOGOUT_USER, AUTH_LOADING, AUTH_ERROR, STOP_LOADING };
