const AUTH_USER = "AUTH_USER";
const LOGOUT_USER = "LOGOUT_USER";
const AUTH_LOADING = "AUTH_LOADING";
const AUTH_ERROR = "AUTH_ERROR";
const STOP_LOADING = "STOP_LOADING";
const GENERAL_LOADING = "GENERAL_LOADING";
const SAVE_GEOLOCATION = "SAVE_GEOLOCATION";
const CLEAR_GENERAL_LOADING = "CLEAR_GENERAL_LOADING";
const CREATE_NEW_RECORD = "CREATE_NEW_RECORD";
const STOP_GENERAL_LOADING = "STOP_GENERAL_LOADING";
const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";

export {
  AUTH_USER,
  LOGOUT_USER,
  AUTH_LOADING,
  AUTH_ERROR,
  STOP_LOADING,
  GENERAL_LOADING,
  SAVE_GEOLOCATION,
  CLEAR_GENERAL_LOADING,
  CREATE_NEW_RECORD,
  STOP_GENERAL_LOADING,
  OPEN_MODAL,
  CLOSE_MODAL
};
